# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc7ef46a2c7ff7f929bcf2d21ff5aec71ce5ceea33891b56da00605e5e907b4615bae907c66c4c559ea21e05013becbb1cc8087582336e6c0cde25fc683d6aeb

test:
  secret_key_base: 84f24376fd74e45d755cb0e0afc9e9e09d912fc8a7165ecea5a769274973ffa672eaef1cb9df5289da7ca44afebc170c7723860f4dade2b3247962ff56c0f8a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: fc7ef46a2c7ff7f929bcf2d21ff5aec71ce5ceea33891b56da00605e5e907b4615bae907c66c4c559ea21e05013becbb1cc8087582336e6c0cde25fc683d6aeb
